#!/usr/bin/env python3
"""Replayable certificate: an EXPLICIT endomorphism of the Weyl algebra A_3
that is not an automorphism -- CONDITIONAL on Alpoge's 2026 root claim
(the dim-3 Jacobian counterexample F; construction of F is NOT ours, see
certificates/jacobian-conjecture/verify.py and root_claim.json).

CLAIM TYPE: derived corollary (constructive content of the classical
"Dixmier implies Jacobian" descent), not a discovery. The recipe is the
classical pullback-on-differential-operators construction:

  Belov-Kanel & Kontsevich, arXiv:math/0512171, Introduction (verbatim):
    "It is well-known that DC_n implies JC_n (in particular DC_infty
     implies JC_infty) (see [5], [3]). The argument is very easy. Let
     phi : A^n_k -> A^n_k be a counterexample to JC_n. Then phi is a
     non-invertible etale map, and it induces a pullback homomorphism
     phi*_diff of the algebra of differential operators on A^n_k. The
     endomorphism phi*_diff of the Weyl algebra preserves the degree of
     differential operators. Restricting phi*_diff to zero order
     differential operators, we obtain the usual pullback phi* of
     functions on A^n_k. By our assertion it is not surjective, hence we
     obtain a counterexample to DC_n."
    ([5] = van den Essen, Progress in Math. 190, 2000; [3] = Bass-
     Connell-Wright, Bull. AMS 7 (1982) 287-330.)

THE EXPLICIT OBJECT (m = 3; A_3 has 6 generators x1,x2,x3,d1,d2,d3 with
[d_i, x_j] = delta_ij, [x_i,x_j] = [d_i,d_j] = 0; coefficients in Q):

  Phi(x_i) = F_i(x1,x2,x3)          (the certified Keller map, det JF = -2)
  Phi(d_i) = sum_k B[i][k] d_k      where  B = (JF^T)^{-1} = adj(JF)^T / (-2)

B is a polynomial matrix because det JF = -2 is a nonzero constant. (The
classical statement takes det = 1; nothing below uses det = 1, only that
det JF is a nonzero constant, which leg 1 of verify.py certifies. One may
normalize by replacing f1 with -f1/2 if a det=1 form is wanted.)

WHAT THE MACHINE CHECKS (exact Fraction arithmetic, stdlib only):
  leg 1  det JF == -2 identically (re-derived here; cross-checks verify.py)
  leg 2  B * JF^T == I == JF^T * B as exact polynomial matrices
  leg 3  the defining relations of A_3 are preserved by Phi, computed in a
         normal-ordering Weyl-algebra engine:
           [Phi(d_i), Phi(x_j)] == delta_ij   (9 commutators)
           [Phi(d_i), Phi(d_j)] == 0          (3 commutators; the nontrivial
                                               integrability identity)
           [Phi(x_i), Phi(x_j)] == 0          (3 commutators)
         => Phi extends to an algebra endomorphism of A_3 (A_3 is presented
            by exactly these relations on these 6 generators -- Dixmier 1968,
            standard; NOT machine-checked, see boundary below).
  leg 4  non-surjectivity witness: the two certified collision points
         P = (0,0,-1/4), Q = (1,-3/2,13/2) satisfy F(P) == F(Q) exactly and
         differ in EVERY coordinate; hence no polynomial g has g(F) == x_l
         for any l, so x_l is not in Phi(A_3) (see lemma below)
  engine unit tests + 4 planted-failure negative controls.

THE TWO NON-MACHINE STEPS (documented boundary, both textbook-elementary):
  (i)  A_3 is the quotient of the free algebra on 6 generators by the ideal
       generated by the relations checked in leg 3 (so checking relations on
       generators suffices for Phi to be a well-defined endomorphism).
  (ii) LEMMA (surjectivity => coordinate is a polynomial in F): suppose
       Phi(a) = x_1 for some a in A_3. By the PBW normal form write
       a = g + h, g in C[x], h in the LEFT ideal I = A_3(d_1,d_2,d_3).
       Phi(d_j) lies in I and I is a left ideal, so Phi(h) in I; hence
       x_1 - g(F) = Phi(h) in I. Apply both sides to the constant function
       1 in the module C[x]: every element of I kills 1, so x_1 = g(F)
       identically. Leg 4 refutes this on the collision pair. Therefore
       Phi is NOT surjective, hence not an automorphism. (This replaces,
       and is even more elementary than, BKK's "preserves the degree of
       differential operators" sentence.)

Run:  python3 weyl_endomorphism.py     (exit 0 = certificate verified)
"""
from fractions import Fraction as Q
from math import comb
import sys

# ---------------------------------------------------------------- poly engine
# Q[x1,x2,x3] as {(i,j,k): nonzero Fraction} -- same engine as verify.py.

def pconst(c):
    c = Q(c)
    return {(0, 0, 0): c} if c else {}

X, Y, Z = {(1, 0, 0): Q(1)}, {(0, 1, 0): Q(1)}, {(0, 0, 1): Q(1)}

def padd(*ps):
    out = {}
    for p in ps:
        for m, c in p.items():
            s = out.get(m, Q(0)) + c
            if s: out[m] = s
            elif m in out: del out[m]
    return out

def pmul(a, b):
    out = {}
    for ma, ca in a.items():
        for mb, cb in b.items():
            m = (ma[0] + mb[0], ma[1] + mb[1], ma[2] + mb[2])
            s = out.get(m, Q(0)) + ca * cb
            if s: out[m] = s
            elif m in out: del out[m]
    return out

def pscale(a, c):
    c = Q(c)
    return {m: v * c for m, v in a.items()} if c else {}

def ppow(a, n):
    out = pconst(1)
    for _ in range(n): out = pmul(out, a)
    return out

def pdiff(a, axis):
    out = {}
    for m, c in a.items():
        e = m[axis]
        if e:
            dm = tuple(v - (1 if i == axis else 0) for i, v in enumerate(m))
            out[dm] = out.get(dm, Q(0)) + c * e
    return {m: c for m, c in out.items() if c}

def peval(a, pt):
    x, y, z = pt
    return sum((c * x**m[0] * y**m[1] * z**m[2] for m, c in a.items()), Q(0))

# ---------------------------------------------------------------- the map F
def build_map():
    u = padd(pconst(1), pmul(X, Y))                     # 1 + xy
    w = padd(pconst(4), pscale(pmul(X, Y), 3))          # 4 + 3xy
    f1 = padd(pmul(ppow(u, 3), Z), pmul(pmul(ppow(Y, 2), u), w))
    f2 = padd(Y, pscale(pmul(pmul(X, ppow(u, 2)), Z), 3),
              pscale(pmul(pmul(X, ppow(Y, 2)), w), 3))
    f3 = padd(pscale(X, 2), pscale(pmul(ppow(X, 2), Y), -3),
              pscale(pmul(ppow(X, 3), Z), -1))
    return f1, f2, f3

def jacobian(fs):
    return [[pdiff(f, ax) for ax in (0, 1, 2)] for f in fs]

def det3(rows):
    (a, b, c), (d, e, f), (g, h, i) = rows
    return padd(pmul(a, padd(pmul(e, i), pscale(pmul(f, h), -1))),
                pscale(pmul(b, padd(pmul(d, i), pscale(pmul(f, g), -1))), -1),
                pmul(c, padd(pmul(d, h), pscale(pmul(e, g), -1))))

def adjugate3(M):
    """adj(M) with adj(M)*M = M*adj(M) = det(M)*I, exact."""
    def cof(r, c):
        rs = [i for i in range(3) if i != r]
        cs = [j for j in range(3) if j != c]
        minor = padd(pmul(M[rs[0]][cs[0]], M[rs[1]][cs[1]]),
                     pscale(pmul(M[rs[0]][cs[1]], M[rs[1]][cs[0]]), -1))
        return pscale(minor, (-1) ** (r + c))
    # adj = cofactor matrix transposed
    return [[cof(c, r) for c in range(3)] for r in range(3)]

def mat_mul(A, B):
    return [[padd(*(pmul(A[i][k], B[k][j]) for k in range(3)))
             for j in range(3)] for i in range(3)]

def mat_transpose(A):
    return [[A[j][i] for j in range(3)] for i in range(3)]

def mat_is_identity(A):
    for i in range(3):
        for j in range(3):
            want = pconst(1) if i == j else {}
            if A[i][j] != want:
                return False
    return True

# ------------------------------------------------------- Weyl algebra engine
# A_3 over Q: elements are {(a1,a2,a3,b1,b2,b3): nonzero Fraction} meaning
# sum of  c * x^a * d^b  in NORMAL ORDER (all x's left of all d's).

def wadd(*ws):
    out = {}
    for w in ws:
        for m, c in w.items():
            s = out.get(m, Q(0)) + c
            if s: out[m] = s
            elif m in out: del out[m]
    return out

def wscale(w, c):
    c = Q(c)
    return {m: v * c for m, v in w.items()} if c else {}

def falling(n, k):
    out = 1
    for t in range(k): out *= (n - t)
    return out

def _mono_mul(a, b, c, d):
    """(x^a d^b)(x^c d^d) as a dict, via  d^b x^c = sum_k prod_j C(b_j,k_j)
    (c_j)_(k_j) x^(c-k) d^(b-k)  (Leibniz / normal ordering)."""
    out = {}
    from itertools import product as iproduct
    ranges = [range(min(b[j], c[j]) + 1) for j in range(3)]
    for k in iproduct(*ranges):
        coef = 1
        for j in range(3):
            coef *= comb(b[j], k[j]) * falling(c[j], k[j])
        m = (a[0] + c[0] - k[0], a[1] + c[1] - k[1], a[2] + c[2] - k[2],
             b[0] + d[0] - k[0], b[1] + d[1] - k[1], b[2] + d[2] - k[2])
        out[m] = out.get(m, 0) + coef
    return out

def wmul(u, v):
    out = {}
    for mu, cu in u.items():
        au, bu = mu[:3], mu[3:]
        for mv, cv in v.items():
            av, bv = mv[:3], mv[3:]
            for m, k in _mono_mul(au, bu, av, bv).items():
                s = out.get(m, Q(0)) + cu * cv * k
                if s: out[m] = s
                elif m in out: del out[m]
    return out

def wcomm(u, v):
    return wadd(wmul(u, v), wscale(wmul(v, u), -1))

def w_from_poly(p):
    """Embed Q[x] into A_3 (multiplication operators)."""
    return {(m[0], m[1], m[2], 0, 0, 0): c for m, c in p.items()}

def w_gen_x(i):
    e = [0, 0, 0, 0, 0, 0]; e[i] = 1
    return {tuple(e): Q(1)}

def w_gen_d(i):
    e = [0, 0, 0, 0, 0, 0]; e[3 + i] = 1
    return {tuple(e): Q(1)}

WZERO = {}
WONE = {(0, 0, 0, 0, 0, 0): Q(1)}

# ------------------------------------------------------- the endomorphism Phi
def build_endomorphism(fs, det_value):
    """Phi(x_i) = F_i,  Phi(d_i) = sum_k B[i][k] d_k,  B = adj(JF)^T / det."""
    J = jacobian(fs)
    B = [[pscale(adjugate3(J)[j][i], Q(1, 1) / Q(det_value))  # adj(J)^T / det
          for j in range(3)] for i in range(3)]
    # NOTE: adj(J)^T[i][j] = adj(J)[j][i]; division exact since det is constant.
    Phi_x = [w_from_poly(f) for f in fs]
    Phi_d = [wadd(*(wmul(w_from_poly(B[i][k]), w_gen_d(k)) for k in range(3)))
             for i in range(3)]
    return Phi_x, Phi_d, B, J

def relations_ok(Phi_x, Phi_d, verbose=True, tag=""):
    ok = True
    for i in range(3):
        for j in range(3):
            want = WONE if i == j else WZERO
            got = wcomm(Phi_d[i], Phi_x[j])
            hit = (got == want)
            ok &= hit
            if verbose and not hit:
                print(f"       {tag}[Phi(d{i+1}),Phi(x{j+1})] != "
                      f"{'1' if i==j else '0'}")
    for i in range(3):
        for j in range(i + 1, 3):
            hit = (wcomm(Phi_d[i], Phi_d[j]) == WZERO)
            ok &= hit
            if verbose and not hit:
                print(f"       {tag}[Phi(d{i+1}),Phi(d{j+1})] != 0")
            hit = (wcomm(Phi_x[i], Phi_x[j]) == WZERO)
            ok &= hit
            if verbose and not hit:
                print(f"       {tag}[Phi(x{i+1}),Phi(x{j+1})] != 0")
    return ok

# ---------------------------------------------------------------- the checks
POINTS = [(Q(0), Q(0), Q(-1, 4)),
          (Q(1), Q(-3, 2), Q(13, 2)),
          (Q(-1), Q(3, 2), Q(13, 2))]
TARGET = (Q(-1, 4), Q(0), Q(0))

def main():
    ok = True
    fs = build_map()

    # Engine unit tests -- the Weyl engine must reproduce known identities.
    t1 = (wcomm(w_gen_d(0), w_gen_x(0)) == WONE)          # [d1,x1] = 1
    t2 = (wcomm(w_gen_d(0), w_gen_x(1)) == WZERO)         # [d1,x2] = 0
    # d1^2 * x1^2 = x1^2 d1^2 + 4 x1 d1 + 2
    lhs = wmul({(0,0,0,2,0,0): Q(1)}, {(2,0,0,0,0,0): Q(1)})
    rhs = {(2,0,0,2,0,0): Q(1), (1,0,0,1,0,0): Q(4), (0,0,0,0,0,0): Q(2)}
    t3 = (lhs == rhs)
    unit = t1 and t2 and t3
    print(f"unit   Weyl engine normal-ordering identities: "
          f"{'PASS' if unit else 'FAIL'}")
    ok &= unit

    # Leg 1 -- det JF == -2 identically (canonical-form soundness as in verify.py).
    d = det3(jacobian(fs))
    assert all(c != 0 for c in d.values()), "non-canonical polynomial"
    leg1 = (d == pconst(-2))
    print(f"leg 1  det(JF) == -2 identically: {'PASS' if leg1 else 'FAIL'}")
    ok &= leg1

    # Build Phi.
    Phi_x, Phi_d, B, J = build_endomorphism(fs, -2)

    # Leg 2 -- B is the exact two-sided inverse of JF^T over Q[x].
    JT = mat_transpose(J)
    leg2 = mat_is_identity(mat_mul(B, JT)) and mat_is_identity(mat_mul(JT, B))
    print(f"leg 2  B * JF^T == I == JF^T * B (exact polynomial matrices): "
          f"{'PASS' if leg2 else 'FAIL'}")
    ok &= leg2

    # Leg 3 -- Phi preserves the defining relations of A_3.
    leg3 = relations_ok(Phi_x, Phi_d)
    print(f"leg 3  all 15 defining relations preserved "
          f"([Phi(d_i),Phi(x_j)]=delta, [Phi(d_i),Phi(d_j)]=0, "
          f"[Phi(x_i),Phi(x_j)]=0): {'PASS' if leg3 else 'FAIL'}")
    ok &= leg3

    # Leg 4 -- non-surjectivity witness: collision pair differing in every
    # coordinate (so no coordinate x_l lies in Q[F] = Phi(A_3) cap ... ).
    P, Qpt = POINTS[0], POINTS[1]
    fP = tuple(peval(f, P) for f in fs)
    fQ = tuple(peval(f, Qpt) for f in fs)
    leg4 = (fP == fQ == TARGET) and all(P[l] != Qpt[l] for l in range(3))
    print(f"leg 4  F(P) == F(Q) == (-1/4,0,0) with P,Q differing in every "
          f"coordinate: {'PASS' if leg4 else 'FAIL'}")
    ok &= leg4

    # Control A -- transpose mistake: B' = adj(J)/det = JF^{-1} (not JF^{-T})
    # must break the [Phi(d_i),Phi(x_j)] relations.
    Bt = [[pscale(adjugate3(J)[i][j], Q(-1, 2)) for j in range(3)]
          for i in range(3)]
    Phi_d_bad = [wadd(*(wmul(w_from_poly(Bt[i][k]), w_gen_d(k))
                        for k in range(3))) for i in range(3)]
    ctrl_a = not relations_ok(Phi_x, Phi_d_bad, verbose=False)
    print(f"ctrl A transposed matrix (JF^-1 for JF^-T) rejected by leg 3: "
          f"{'PASS' if ctrl_a else 'FAIL'}")
    ok &= ctrl_a

    # Control B -- perturb one coefficient: B[0][0] += x1. Must break leg 3.
    B2 = [row[:] for row in B]
    B2[0][0] = padd(B2[0][0], X)
    Phi_d_b2 = [wadd(*(wmul(w_from_poly(B2[i][k]), w_gen_d(k))
                       for k in range(3))) for i in range(3)]
    ctrl_b = not relations_ok(Phi_x, Phi_d_b2, verbose=False)
    print(f"ctrl B perturbed coefficient (B11 + x1) rejected by leg 3: "
          f"{'PASS' if ctrl_b else 'FAIL'}")
    ok &= ctrl_b

    # Control C -- perturbed map (f3 + x1 x2): det is no longer constant, and
    # the naive adj^T/(-2) recipe must fail the relations.
    fs_bad = (fs[0], fs[1], padd(fs[2], pmul(X, Y)))
    ctrl_c1 = (det3(jacobian(fs_bad)) != pconst(-2))
    Phi_x_c, Phi_d_c, _, _ = build_endomorphism(fs_bad, -2)
    ctrl_c2 = not relations_ok(Phi_x_c, Phi_d_c, verbose=False)
    ctrl_c = ctrl_c1 and ctrl_c2
    print(f"ctrl C perturbed map (f3 + x1x2) rejected (det and leg 3): "
          f"{'PASS' if ctrl_c else 'FAIL'}")
    ok &= ctrl_c

    # Control D -- perturbed point must miss the target (leg 4 can reject).
    bad = (Q(1), Q(-3, 2), Q(13, 2) + Q(1, 100))
    ctrl_d = tuple(peval(f, bad) for f in fs) != TARGET
    print(f"ctrl D perturbed point rejected by leg 4: "
          f"{'PASS' if ctrl_d else 'FAIL'}")
    ok &= ctrl_d

    if ok:
        n_terms = [len(Phi_d[i]) for i in range(3)]
        deg = max(sum(m[:3]) for i in range(3) for m in Phi_d[i])
        print("\nEXPLICIT OBJECT: Phi : A_3 -> A_3,  Phi(x_i) = F_i,  "
              "Phi(d_i) = sum_k (adj(JF)^T/(-2))[i][k] d_k")
        print(f"  Phi(d_i) term counts {n_terms}, max coefficient degree {deg}; "
              "all 15 relations verified exactly over Q.")
        print("CERTIFICATE VERIFIED (conditional on the root claim): Phi is a "
              "well-defined endomorphism of A_3; by the PBW lemma in the "
              "header + leg 4 it is NOT surjective, hence NOT an automorphism "
              "=> Dixmier Conjecture DC_3 fails (and DC_n for n >= 3 by "
              "BKK's 'DC_n implies DC_m for n > m').")
    else:
        print("\nCERTIFICATE FAILED -- see legs above")
    return 0 if ok else 1

if __name__ == "__main__":
    sys.exit(main())
