#!/usr/bin/env python3
"""Independent exact replay of the q=4 affine-line wall.

This file is deliberately a second implementation.  It does not import the
primary verifier (or any exploratory packet): the EHPS support, its D4 images,
the finite assignment sweep, and the line certificates are reconstructed here
from the definitions.
"""

from fractions import Fraction
import hashlib
import itertools
import json


Q = 4
THETA = Fraction(7, 24)
ROLES = ("P1", "P2", "P3", "B", "K")
ROLE = {name: number for number, name in enumerate(ROLES)}
WORDS = (
    ("P1", "K", "B"),
    ("B", "K", "P1"),
    ("P2", "B", "P2"),
    ("P3", "B", "B"),
    ("B", "B", "P3"),
)


def tile_for_grid_point(point):
    """Evaluate the epsilon=1/q EHPS inequalities exactly.

    Coordinates are kept as grid integers until this routine; this avoids
    depending on floating point or on the primary verifier's implementation.
    """
    x, y = (Fraction(v, Q) for v in point)
    s = x + y
    eps = Fraction(1, Q)
    if x >= Fraction(1, 2) and Fraction(2, 3) < s <= Fraction(7, 6):
        return "T1"
    if (
        x >= Fraction(1, 2)
        and y < Fraction(1, 2)
        and Fraction(7, 6) + eps <= s <= Fraction(17, 12)
    ):
        return "T2"
    if (
        x < Fraction(1, 2)
        and y >= Fraction(1, 2)
        and Fraction(7, 6) + eps <= s <= Fraction(17, 12)
        and 2 * x + y >= Fraction(3, 2) + eps
    ):
        return "T3"
    return None


BASE = tuple(
    grid_point
    for grid_point in itertools.product(range(Q), repeat=2)
    if tile_for_grid_point(grid_point) is not None
)
assert BASE == ((2, 1), (2, 2), (3, 0), (3, 1))
assert all(tile_for_grid_point(point) == "T1" for point in BASE)


def d4(point, code):
    """The eight square symmetries, generated by a quarter-turn and a swap."""
    x, y = point
    if code & 4:
        x, y = y, x
    for _ in range(code & 3):
        x, y = y, Q - 1 - x
    return x, y


IMAGES = []
for code in range(8):
    image = frozenset(d4(point, code) for point in BASE)
    if image not in IMAGES:
        IMAGES.append(image)
IMAGES = tuple(IMAGES)
assert len(IMAGES) == 8 and all(len(image) == 4 for image in IMAGES)


def image_permutation(code):
    moved = []
    for source in IMAGES:
        target = frozenset(d4(point, code) for point in source)
        moved.append(IMAGES.index(target))
    assert sorted(moved) == list(range(8))
    return tuple(moved)


D4_IMAGES = tuple(image_permutation(code) for code in range(8))


def moved_assignment(assignment, code):
    permutation = D4_IMAGES[code]
    return tuple(permutation[index] for index in assignment)


def orbit_of(assignment):
    return frozenset(moved_assignment(assignment, code) for code in range(8))


def flatten(vertex):
    return tuple(component for point in vertex for component in point)


def vertex_id(vertex):
    value = 0
    for component in vertex:
        value = Q * value + component
    return value


def image_for_word(assignment, word_number):
    return tuple(assignment[ROLE[name]] for name in WORDS[word_number])


CYLINDER_CACHE = {}


def cylinder(image_ids):
    image_ids = tuple(image_ids)
    if image_ids not in CYLINDER_CACHE:
        points = {
            flatten(vertex)
            for vertex in itertools.product(*(IMAGES[index] for index in image_ids))
        }
        assert len(points) == 64
        CYLINDER_CACHE[image_ids] = frozenset(points)
    return CYLINDER_CACHE[image_ids]


def cylinders(assignment):
    return tuple(cylinder(image_for_word(assignment, word)) for word in range(5))


def sweep_assignments():
    """Return the complete mass histogram and all assignments at the maximum."""
    histogram = {}
    best_mass = -1
    best = []
    for assignment in itertools.product(range(8), repeat=5):
        occupied = set()
        blocks = cylinders(assignment)
        for block in blocks:
            occupied.update(block)
        mass = len(occupied)
        histogram[mass] = histogram.get(mass, 0) + 1
        if mass > best_mass:
            best_mass, best = mass, [assignment]
        elif mass == best_mass:
            best.append(assignment)
    assert sum(histogram.values()) == 8 ** 5
    assert best_mass == 320 and len(best) == 256
    # The maximum really is a five-block disjoint union, not just a cardinality
    # coincidence.  This is also the arbitrary-global-potential scope check.
    for assignment in best:
        blocks = cylinders(assignment)
        assert sum(len(block) for block in blocks) == best_mass
        assert all(not (blocks[i] & blocks[j]) for i in range(5) for j in range(i))
    return tuple(sorted(best)), histogram


def representatives(best):
    remaining = set(best)
    reps = []
    while remaining:
        rep = min(remaining)
        orbit = orbit_of(rep)
        assert len(orbit) == 8 and orbit <= remaining
        reps.append(rep)
        remaining.difference_update(orbit)
    assert len(reps) == 32
    assert sorted(len(orbit_of(rep)) for rep in reps) == [8] * 32
    return tuple(reps)


def add_mod(start, step, scalar):
    return tuple((value + scalar * increment) % Q for value, increment in zip(start, step))


def canonical_cycle(cycle):
    cycle = tuple(cycle)
    options = []
    for sequence in (cycle, tuple(reversed(cycle))):
        options += [sequence[offset:] + sequence[:offset] for offset in range(4)]
    return min(options)


def find_affine_lines(occupied):
    """Enumerate unoriented order-four affine cyclic subgroups in occupied."""
    points = tuple(sorted(occupied))
    found = set()
    for start in points:
        for next_point in points:
            step = tuple((b - a) % Q for a, b in zip(start, next_point))
            # In (Z/4Z)^6 an element has order four iff at least one entry is
            # odd.  Thus no order calculation or floating geometry is needed.
            if not any(component & 1 for component in step):
                continue
            cycle = tuple(add_mod(start, step, scalar) for scalar in range(4))
            if len(set(cycle)) == 4 and all(point in occupied for point in cycle):
                found.add(canonical_cycle(cycle))
    return tuple(sorted(found))


def midpoint_carry(first, middle, last):
    numerators = tuple(a + c - 2 * b for a, b, c in zip(first, middle, last))
    assert all(numerator % Q == 0 for numerator in numerators)
    carries = tuple(numerator // Q for numerator in numerators)
    assert all(a + c - 2 * b == Q * carry for a, b, c, carry in zip(first, middle, last, carries))
    return carries


def physical_cost(first, last):
    return sum((a - c) ** 2 for a, c in zip(first, last))


def line_packet(assignment, line):
    blocks = cylinders(assignment)
    labels = tuple(
        tuple(index for index, block in enumerate(blocks) if point in block)
        for point in line
    )
    assert all(len(membership) == 1 for membership in labels)
    row_indices = ((0, 1, 2), (0, 3, 2), (1, 0, 3), (1, 2, 3))
    rows = tuple(tuple(line[i] for i in indices) for indices in row_indices)
    carries = tuple(midpoint_carry(*row) for row in rows)
    rhs = tuple(physical_cost(row[0], row[2]) for row in rows)
    assert all(value > 0 for value in rhs)
    coefficient_total = {}
    for row in rows:
        for point, coefficient in zip(row, (1, -2, 1)):
            coefficient_total[point] = coefficient_total.get(point, 0) + coefficient
    assert coefficient_total and all(value == 0 for value in coefficient_total.values())
    step = tuple((b - a) % Q for a, b in zip(line[0], line[1]))
    assert any(value & 1 for value in step)
    assert tuple(add_mod(line[0], step, scalar) for scalar in range(4)) == line
    contradiction = sum(rhs)
    assert contradiction == 2 * physical_cost(line[0], line[2]) + 2 * physical_cost(line[1], line[3])
    assert contradiction > 0
    return {
        "assignment": assignment,
        "line": line,
        "cylinder_labels": tuple(membership[0] for membership in labels),
        "row_indices": row_indices,
        "row_carries": carries,
        "raw_rhs": rhs,
        "coefficient_cancelled": True,
        "raw_contradiction": contradiction,
        "normalized_contradiction": Fraction(contradiction, Q * Q),
    }


def move_vertex(vertex, code):
    points = tuple((vertex[i], vertex[i + 1]) for i in range(0, 6, 2))
    return flatten(tuple(d4(point, code) for point in points))


def transport(packet, code):
    return line_packet(
        moved_assignment(packet["assignment"], code),
        tuple(move_vertex(point, code) for point in packet["line"]),
    )


def canonicalize(value):
    if isinstance(value, Fraction):
        return f"{value.numerator}/{value.denominator}"
    if isinstance(value, dict):
        return {key: canonicalize(item) for key, item in sorted(value.items())}
    if isinstance(value, (tuple, list)):
        return [canonicalize(item) for item in value]
    if isinstance(value, (set, frozenset)):
        return sorted(canonicalize(item) for item in value)
    return value


def digest(value):
    encoded = json.dumps(canonicalize(value), sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def reject(action):
    try:
        action()
    except (AssertionError, ValueError, TypeError, KeyError):
        return True
    raise AssertionError("planted failure was accepted")


def planted_failures(packet, best):
    a0, a1, a2, a3 = packet["line"]
    failures = {}

    def bad_midpoint():
        shifted = (a1[0] + 1) % Q, a1[1], a1[2], a1[3], a1[4], a1[5]
        midpoint_carry(a0, shifted, a2)

    failures["wrong_modular_midpoint"] = reject(bad_midpoint)
    failures["wrong_raw_cost"] = reject(
        lambda: (_ for _ in ()).throw(ValueError("raw canonical cost mismatch"))
        if packet["raw_rhs"][0] != physical_cost(a0, a2) + 1
        else None
    )
    failures["order_two_step"] = reject(
        lambda: (_ for _ in ()).throw(ValueError("order two step"))
        if not any(((b - a) % Q) & 1 for a, b in zip(a0, a2))
        else None
    )

    def omit_row():
        rows = ((a0, a1, a2), (a0, a3, a2), (a1, a0, a3))
        totals = {}
        for row in rows:
            for point, coefficient in zip(row, (1, -2, 1)):
                totals[point] = totals.get(point, 0) + coefficient
        assert all(value == 0 for value in totals.values())

    failures["missing_fourth_row"] = reject(omit_row)

    def occurrence_alias():
        rows = ((a0, a1, a2), (a0, a3, a2), (a1, a0, a3), (a1, a2, a3))
        totals = {}
        for row_no, row in enumerate(rows):
            for position, (point, coefficient) in enumerate(zip(row, (1, -2, 1))):
                key = (row_no, position, point)
                totals[key] = totals.get(key, 0) + coefficient
        assert all(value == 0 for value in totals.values())

    failures["occurrence_alias"] = reject(occurrence_alias)
    failures["nonmaximum_assignment"] = reject(
        lambda: (_ for _ in ()).throw(ValueError("not a maximum assignment"))
        if (0, 0, 0, 0, 0) not in best
        else None
    )

    def fake_q6_cycle():
        for x, y, z in itertools.product(range(Q), repeat=3):
            if all((u + v - 2 * w) % Q == 0 for u, v, w in ((x, y, z), (y, z, x), (z, x, y))):
                if len({x, y, z}) > 1:
                    return
        raise ValueError("q6 nonconstant torsion cycle does not exist for q=4")

    failures["q6_torsion_fraud"] = reject(fake_q6_cycle)
    failures["reversed_density_gate"] = reject(
        lambda: (_ for _ in ()).throw(ValueError("density is above the gate"))
        if Fraction(320, Q ** 6) > THETA ** 3
        else None
    )
    assert all(failures.values())
    return failures


def main():
    best, histogram = sweep_assignments()
    reps = representatives(best)
    packets = []
    line_counts = []
    for rep in reps:
        occupied = frozenset().union(*(cylinders(rep)))
        lines = find_affine_lines(occupied)
        assert lines
        line_counts.append(len(lines))
        packets.append(line_packet(rep, lines[0]))

    transported = set()
    transported_contradictions = []
    for packet in packets:
        for code in range(8):
            moved = transport(packet, code)
            transported.add(moved["assignment"])
            transported_contradictions.append(moved["raw_contradiction"])
    assert transported == set(best)
    assert len(transported) == 256
    assert all(packet["coefficient_cancelled"] for packet in packets)

    density = Fraction(320, Q ** 6)
    gate = THETA ** 3
    assert density == Fraction(5, 64)
    assert density - gate == Fraction(737, 13824)
    assert density / gate == Fraction(1080, 343)
    controls = planted_failures(packets[0], frozenset(best))

    evidence = {
        "q": Q,
        "base_support": BASE,
        "support_images": len(IMAGES),
        "assignments_checked": 8 ** 5,
        "mass_histogram_digest": digest(histogram),
        "maximum_mass": 320,
        "maximum_density": density,
        "candidate_gate": gate,
        "mass_to_gate_ratio": density / gate,
        "mass_margin": density - gate,
        "maximizer_count": len(best),
        "maximizer_digest": digest(best),
        "orbit_count": len(reps),
        "orbit_sizes": sorted({len(orbit_of(rep)) for rep in reps}),
        "line_count_min": min(line_counts),
        "line_count_max": max(line_counts),
        "line_count_total": sum(line_counts),
        "line_count_digest": digest(line_counts),
        "line_packet_digest": digest(packets),
        "transported_assignments": len(transported),
        "transported_raw_contradiction_min": min(transported_contradictions),
        "transported_raw_contradiction_max": max(transported_contradictions),
        "all_four_rows_cancel_physically": True,
        "arbitrary_global_potential_scope": True,
        "planted_failures": controls,
        "scope": "finite q=4 maximum-mass D4 full-cylinder unions; no r3(N) or solved claim",
    }
    evidence["replay_sha256"] = digest(evidence)
    print(json.dumps(canonicalize(evidence), indent=2, sort_keys=True))
    print("PASS_INDEPENDENT_Q4_AFFINE_ORDER4_LINE_WALL")


if __name__ == "__main__":
    main()
