#!/usr/bin/env python3
"""Independent stdlib-only replay of the finite q=6 outer-code wall.

This file deliberately does not import the sibling verify.py or any atlas
module.  It rebuilds the eight square images, the five word cylinders, and
the three-torsion table from scratch.  The outer argument is checked by
concatenating physical vertices and carries, never by tensoring potentials.
"""

from fractions import Fraction
from functools import lru_cache
import hashlib
import itertools
import json


Q = 6
ROLES = ("P1", "P2", "P3", "B", "K")
ROLE_INDEX = {name: index for index, name in enumerate(ROLES)}
WORDS = (
    ("P1", "K", "B"),
    ("B", "K", "P1"),
    ("P2", "B", "P2"),
    ("P3", "B", "B"),
    ("B", "B", "P3"),
)
BASE = frozenset(
    ((3, 2), (3, 3), (3, 4), (4, 1), (4, 2),
     (4, 3), (5, 0), (5, 1), (5, 2))
)


def square_image(point, operation):
    """The eight D4 images, generated by two reflections and a swap."""
    x, y = point
    # This is a direct group-table derivation, rather than importing the
    # image table from the primary replay.  The bit order is fixed only so
    # the assignment census is deterministic.
    if operation & 1:
        x = Q - 1 - x
    if operation & 2:
        y = Q - 1 - y
    if operation & 4:
        x, y = y, x
    return x, y


IMAGES = []
for operation in range(8):
    image = frozenset(square_image(p, operation) for p in BASE)
    if image not in IMAGES:
        IMAGES.append(image)
assert len(IMAGES) == 8 and all(len(s) == 9 for s in IMAGES)


def word_support_ids(assignment, word_number):
    return tuple(
        assignment[ROLE_INDEX[role]] for role in WORDS[word_number]
    )


def flatten(value):
    out = []
    if isinstance(value, int):
        return (value,)
    for item in value:
        out.extend(flatten(item))
    return tuple(out)


def point_cost(first, last):
    return sum((a - b) ** 2 for a, b in zip(flatten(first), flatten(last)))


@lru_cache(maxsize=None)
def cylinder(s0, s1, s2):
    return frozenset(itertools.product(IMAGES[s0], IMAGES[s1], IMAGES[s2]))


def cylinders(assignment):
    return tuple(cylinder(*word_support_ids(assignment, word))
                 for word in range(5))


def union_mass(assignment):
    union = set()
    for support in cylinders(assignment):
        union.update(support)
    return len(union)


def census():
    best = -1
    maxima = []
    assignment_count = 0
    for assignment in itertools.product(range(8), repeat=5):
        assignment_count += 1
        mass = union_mass(assignment)
        if mass > best:
            best, maxima = mass, [assignment]
        elif mass == best:
            maxima.append(assignment)
    assert assignment_count == 8 ** 5
    assert best == 3645 and len(maxima) == 256
    for assignment in maxima:
        cs = cylinders(assignment)
        assert all(cs[i].isdisjoint(cs[j])
                   for i in range(5) for j in range(i + 1, 5))
        assert all(len(support) == 729 for support in cs)
    return tuple(maxima)


POINTS = tuple(itertools.product(range(Q), repeat=2))
TORSION = []
for x in POINTS:
    for y in POINTS:
        z = tuple((2 * y[j] - x[j]) % Q for j in range(2))
        # Check all three centers.  The first equation alone is not enough
        # for a three-row cancelling triangle.
        if all((x[j] + z[j] - 2 * y[j]) % Q == 0 and
               (y[j] + z[j] - 2 * x[j]) % Q == 0 and
               (x[j] + y[j] - 2 * z[j]) % Q == 0
               for j in range(2)):
            TORSION.append((x, y, z))
TORSION = tuple(TORSION)
assert len(TORSION) == 324


def nonconstant(triple):
    return triple[0] != triple[1] or triple[1] != triple[2]


def local_membership(vertex, assignment, word):
    if len(vertex) != 3:
        return False
    return all(
        vertex[position] in IMAGES[assignment[ROLE_INDEX[role]]]
        for position, role in enumerate(WORDS[word])
    )


@lru_cache(maxsize=None)
def local_cycle(assignment, a, b, c):
    """Return a common positive triangle for a non-diagonal word pattern."""
    if a == b == c:
        raise AssertionError("diagonal pattern has only the constant cycle")
    factors = []
    for position in range(3):
        sx = assignment[ROLE_INDEX[WORDS[a][position]]]
        sy = assignment[ROLE_INDEX[WORDS[b][position]]]
        sz = assignment[ROLE_INDEX[WORDS[c][position]]]
        allowed = tuple(
            triple for triple in TORSION
            if triple[0] in IMAGES[sx]
            and triple[1] in IMAGES[sy]
            and triple[2] in IMAGES[sz]
        )
        if not allowed:
            return None
        factors.append(allowed)

    selected = [factor[0] for factor in factors]
    for position, factor in enumerate(factors):
        candidate = next((triple for triple in factor if nonconstant(triple)), None)
        if candidate is not None:
            selected[position] = candidate
            break
    else:
        return None

    x = tuple(triple[0] for triple in selected)
    y = tuple(triple[1] for triple in selected)
    z = tuple(triple[2] for triple in selected)
    assert local_membership(x, assignment, a)
    assert local_membership(y, assignment, b)
    assert local_membership(z, assignment, c)
    rows = ((x, y, z), (y, x, z), (x, z, y))
    carries = tuple(midpoint_carry(*row) for row in rows)
    rhs = tuple(point_cost(row[0], row[2]) for row in rows)
    assert sum(rhs) > 0
    return x, y, z, rhs, carries


def midpoint_carry(first, center, last):
    a, b, c = flatten(first), flatten(center), flatten(last)
    if not (len(a) == len(b) == len(c)):
        raise AssertionError("dimension mismatch")
    numerators = tuple(x + z - 2 * y for x, y, z in zip(a, b, c))
    if any(n % Q for n in numerators):
        raise AssertionError("midpoint congruence failure")
    carries = tuple(n // Q for n in numerators)
    assert all(x + z - 2 * y == Q * k
               for x, y, z, k in zip(a, b, c, carries))
    return carries


def constant_cycle(assignment, word):
    points = tuple(
        min(IMAGES[assignment[ROLE_INDEX[role]]])
        for role in WORDS[word]
    )
    assert local_membership(points, assignment, word)
    assert all(point_cost(points, points) == 0 for _ in range(3))
    rows = ((points, points, points),) * 3
    return points, points, points, (0, 0, 0), tuple(
        midpoint_carry(*row) for row in rows
    )


def product_membership(vertex, assignments, word):
    return len(vertex) == len(assignments) == len(word) and all(
        local_membership(vertex[i], assignments[i], word[i])
        for i in range(len(word))
    )


def coefficient_sum(rows):
    coefficients = {}
    for first, center, last in rows:
        for vertex, coefficient in ((first, 1), (center, -2), (last, 1)):
            coefficients[vertex] = coefficients.get(vertex, 0) + coefficient
    return {vertex: value for vertex, value in coefficients.items() if value}


def tensor_pair(assignments, u, v, maxima):
    assignments, u, v = tuple(assignments), tuple(u), tuple(v)
    if len(assignments) != len(u) or len(u) != len(v) or not u:
        raise AssertionError("outer length mismatch")
    if u == v:
        raise AssertionError("equal outer words are not a pair")
    if any(assignment not in maxima for assignment in assignments):
        raise AssertionError("nonmaximum local assignment")

    local = []
    differing = []
    for index, (assignment, a, b) in enumerate(zip(assignments, u, v)):
        if a == b:
            local.append(constant_cycle(assignment, a))
        else:
            cycle = local_cycle(assignment, a, b, b)
            if cycle is None:
                raise AssertionError("missing repeated-word local cycle")
            local.append(cycle)
            differing.append(index)
    assert differing

    x = tuple(item[0] for item in local)
    y = tuple(item[1] for item in local)
    z = tuple(item[2] for item in local)
    rows = ((x, y, z), (y, x, z), (x, z, y))
    rhs = tuple(point_cost(row[0], row[2]) for row in rows)
    local_rhs = tuple(item[3] for item in local)
    expected_rhs = tuple(sum(item[3][j] for item in local) for j in range(3))
    assert rhs == expected_rhs
    carries = tuple(midpoint_carry(*row) for row in rows)
    expected_carries = tuple(
        tuple(value for item in local for value in item[4][row])
        for row in range(3)
    )
    assert carries == expected_carries
    assert product_membership(x, assignments, u)
    assert product_membership(y, assignments, v)
    assert product_membership(z, assignments, v)
    assert coefficient_sum(rows) == {}
    assert sum(rhs) >= 24 * len(differing)
    packet = {
        "vertices": (x, y, z),
        "rows": rows,
        "rhs": rhs,
        "local_rhs": local_rhs,
        "carries": carries,
        "differing": tuple(differing),
    }
    validate_tensor_packet(packet, assignments, u, v)
    return packet


def validate_tensor_packet(packet, assignments, u, v):
    """Recompute every semantic field from the three physical global points."""
    x, y, z = packet["vertices"]
    rows = ((x, y, z), (y, x, z), (x, z, y))
    if packet["rows"] != rows:
        raise AssertionError("global row identity failure")
    if not product_membership(x, assignments, u):
        raise AssertionError("X membership failure")
    if not product_membership(y, assignments, v):
        raise AssertionError("Y membership failure")
    if not product_membership(z, assignments, v):
        raise AssertionError("Z membership failure")
    carries = tuple(midpoint_carry(*row) for row in rows)
    if packet["carries"] != carries:
        raise AssertionError("carry field failure")
    rhs = tuple(point_cost(row[0], row[2]) for row in rows)
    if packet["rhs"] != rhs:
        raise AssertionError("raw cost field failure")
    expected = tuple(sum(item[j] for item in packet["local_rhs"])
                     for j in range(3)) if "local_rhs" in packet else None
    if expected is not None and rhs != expected:
        raise AssertionError("local-to-global cost additivity failure")
    if coefficient_sum(rows):
        raise AssertionError("global potential coefficients do not cancel")


def expect_failure(callback):
    try:
        callback()
    except (AssertionError, KeyError, TypeError, ValueError):
        return True
    raise AssertionError("planted failure was accepted")


def controls(packet, assignments, u, v, maxima):
    x, y, z = packet["vertices"]
    result = {}

    def bad_midpoint():
        bad = list(x)
        point = list(bad[0][0])
        point[0] = (point[0] + 1) % Q
        bad[0] = (tuple(point),) + bad[0][1:]
        midpoint_carry(tuple(bad), y, z)

    result["wrong_midpoint_rejected"] = expect_failure(bad_midpoint)

    def bad_carry():
        bad = dict(packet)
        claimed = tuple(tuple(c) for c in packet["carries"])
        altered = [list(c) for c in claimed]
        altered[0][0] += 1
        bad["carries"] = tuple(tuple(c) for c in altered)
        validate_tensor_packet(bad, assignments, u, v)

    result["wrong_carry_rejected"] = expect_failure(bad_carry)

    def bad_cost():
        bad = dict(packet)
        claimed = list(packet["rhs"])
        claimed[0] += 1
        bad["rhs"] = tuple(claimed)
        validate_tensor_packet(bad, assignments, u, v)

    result["wrong_raw_cost_rejected"] = expect_failure(bad_cost)

    def projection_alias():
        bad = dict(packet)
        hybrid = (y[0],) + x[1:]
        bad["rows"] = ((x, y, z), (hybrid, x, z), (x, z, y))
        validate_tensor_packet(bad, assignments, u, v)

    result["coordinate_projection_identity_rejected"] = expect_failure(
        projection_alias
    )

    def occurrence_alias():
        tagged = tuple(
            tuple((row_number, position, vertex)
                  for position, vertex in enumerate(row))
            for row_number, row in enumerate(packet["rows"])
        )
        if coefficient_sum(tagged):
            raise AssertionError("occurrence labels do not cancel")

    result["occurrence_label_alias_rejected"] = expect_failure(occurrence_alias)
    result["equal_codeword_rejected"] = expect_failure(
        lambda: tensor_pair(assignments, u, u, maxima)
    )
    bad_assignments = (next(a for a in itertools.product(range(8), repeat=5)
                            if a not in maxima),) + assignments[1:]
    result["nonmaximum_coordinate_rejected"] = expect_failure(
        lambda: tensor_pair(bad_assignments, u, v, maxima)
    )

    def overbroad_nonmax_claim():
        bad = (0, 0, 0, 0, 0)
        assert union_mass(bad) == 729
        assert local_cycle(bad, 0, 1, 1) is not None

    result["nonmax_counterexample_rejected"] = expect_failure(
        overbroad_nonmax_claim
    )
    assert all(result.values())
    return result


def main():
    maxima = census()
    maximum_set = frozenset(maxima)

    pair_sums = []
    pair_records = []
    for assignment in maxima:
        for a in range(5):
            for b in range(5):
                if a == b:
                    continue
                cycle = local_cycle(assignment, a, b, b)
                assert cycle is not None
                pair_sums.append(sum(cycle[3]))
                pair_records.append((assignment, a, b, cycle[3], cycle[4]))
    assert len(pair_sums) == 256 * 20
    assert min(pair_sums) == 24 and max(pair_sums) == 144

    # Length-seven product with coordinate-dependent maximum assignments and
    # four differing coordinates.  This checks the complete global identity,
    # not merely a separable proxy.
    assignments = tuple(maxima[(37 * i + 11) % len(maxima)] for i in range(7))
    u = (0, 1, 2, 3, 4, 0, 2)
    v = (0, 4, 2, 1, 4, 3, 0)
    packet = tensor_pair(assignments, u, v, maximum_set)
    assert packet["differing"] == (1, 3, 5, 6)
    assert sum(packet["rhs"]) >= 24 * len(packet["differing"])

    # Deliberately nonseparable values on full physical vertices.
    x, y, z = packet["vertices"]
    values = {x: 137, y: -211, z: 43}
    lhs = sum(values[first] - 2 * values[center] + values[last]
              for first, center, last in packet["rows"])
    assert lhs == 0 and sum(packet["rhs"]) > 0

    densities = []
    for length in (1, 2, 7, 19):
        density = Fraction(1, 64) ** length
        gate = Fraction(7, 24) ** (3 * length)
        assert density < gate
        densities.append({"length": length, "density": str(density),
                          "gate": str(gate)})

    planted = controls(packet, assignments, u, v, maximum_set)
    records_digest = hashlib.sha256(
        json.dumps(pair_records, sort_keys=True, separators=(",", ":"),
                   default=list).encode("ascii")
    ).hexdigest()
    output = {
        "q": Q,
        "assignment_count": 8 ** 5,
        "maximum_union_mass": 3645,
        "maximizer_count": len(maxima),
        "local_cylinder_size": 729,
        "ambient_local_size": 6 ** 6,
        "point_torsion_count": len(TORSION),
        "pair_patterns_checked": len(pair_sums),
        "pair_pattern_count": 20,
        "pair_rhs_sum_min": min(pair_sums),
        "pair_rhs_sum_max": max(pair_sums),
        "pair_record_digest": records_digest,
        "outer_length_symbolic_constructor": True,
        "coordinate_dependent_maximizers": True,
        "global_potential_separable_assumption": False,
        "global_coefficients_cancel": True,
        "global_carries_concatenate": True,
        "global_raw_cost_additive": True,
        "outer_hamming_floor_raw": 24,
        "outer_hamming_floor_normalized": "2/3",
        "sample_length": 7,
        "sample_differing_coordinates": list(packet["differing"]),
        "sample_rhs": list(packet["rhs"]),
        "singleton_density": "1/64",
        "candidate_singleton_gate": str(Fraction(7, 24) ** 3),
        "singleton_below_gate": True,
        "density_samples": densities,
        "controls": planted,
        "scope": (
            "finite Cartesian products of exact q=6 maximum-mass D4 cylinders; "
            "no thickening, deformed supports, scalar transfer, r3 bound, or solution"
        ),
    }
    text = json.dumps(output, indent=2, sort_keys=True) + "\n"
    print(text, end="")
    print("result_sha256", hashlib.sha256(text.encode("utf-8")).hexdigest())
    print("PASS_INDEPENDENT_Q6_OUTERCODE_TENSOR_WALL")


if __name__ == "__main__":
    main()
